package com.xafdy.entity;
// Generated 2018-4-23 22:10:40 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name = "item", catalog = "lvyou")
public class Item implements java.io.Serializable {

	private Integer id;
	private String name;
	private String address;
	private int price;
	private int days;
	private String feature;
	private String intro;
	private String path;
	private String city;
	private Set<Comment> comments = new HashSet<Comment>(0);
	private Set<Foods> foodses = new HashSet<Foods>(0);

	public Item() {
	}

	public Item(String name, String address, int price, int days, String feature, String intro) {
		this.name = name;
		this.address = address;
		this.price = price;
		this.days = days;
		this.feature = feature;
		this.intro = intro;
	}

	public Item(String name, String address, int price, int days, String feature, String intro, String path,
			String city, Set<Comment> comments, Set<Foods> foodses) {
		this.name = name;
		this.address = address;
		this.price = price;
		this.days = days;
		this.feature = feature;
		this.intro = intro;
		this.path = path;
		this.city = city;
		this.comments = comments;
		this.foodses = foodses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address", nullable = false, length = 65535)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "price", nullable = false)
	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	@Column(name = "days", nullable = false)
	public int getDays() {
		return this.days;
	}

	public void setDays(int days) {
		this.days = days;
	}

	@Column(name = "feature", nullable = false, length = 50)
	public String getFeature() {
		return this.feature;
	}

	public void setFeature(String feature) {
		this.feature = feature;
	}

	@Column(name = "intro", nullable = false, length = 65535)
	public String getIntro() {
		return this.intro;
	}

	public void setIntro(String intro) {
		this.intro = intro;
	}

	@Column(name = "path", length = 65535)
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@Column(name = "city", length = 50)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "item")
	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "item")
	public Set<Foods> getFoodses() {
		return this.foodses;
	}

	public void setFoodses(Set<Foods> foodses) {
		this.foodses = foodses;
	}

}
